GET http://localhost:5500/stands/


###
GET http://localhost:5500/stands/2


###
POST http://localhost:5500/stands/
Content-Type: application/json

{"sector": "Pabellón 2 - Artesanías", "numeroStand": "A-22"}

###

